### Coca Cola
POST http://127.0.0.1:8000/api/barcode/00605388872074/
Content-Type: application/json

{
    "energy_profile_factor": 0.25,
    "saturation_profile_factor": 0.25,
    "sugars_profile_factor": 0.25,
    "sodium_profile_factor": 0.25,
    "max_additives_penalty": 50,
    "non_organic_penalty": 10
}

### Earth Own Unweetened Oat Milk
POST http://127.0.0.1:8000/api/barcode/00626027841022/
Content-Type: application/json

### Minute Rice
POST http://127.0.0.1:8000/api/barcode/00059100008027/
Content-Type: application/json

### Chosen Foods Avocado Oil
POST http://127.0.0.1:8000/api/barcode/00853807005828/
Content-Type: application/json

### Lean Ground Beef
POST http://127.0.0.1:8000/api/barcode/628915825206/
Content-Type: application/json

### Great value  cheddar cheese (extract has problem)
POST http://127.0.0.1:8000/api/barcode/68200885117/
Content-Type: application/json